language: android
env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
  - ./gradlew checkstyle build